services:
  postgres-demo:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ev_demo
      POSTGRES_USER: ev_user
      POSTGRES_PASSWORD: ev_pass
    volumes:
      - pgdata_demo:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ev_user -d ev_demo"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  pgdata_demo:
